In [ ]:
Numpy, Pandas, Scipy, Matplotlib, Seaborn, Plotly   

In [ ]:
Numpy - Numerical Python
Numpy is used for computation and manipulation of 1D and ND Array.

In [ ]:
Documented, Image, Audio, Video - Array



In [41]:
import sys
lst = list(range(10))
# [i*2 for i in lst]
print(sys.getsizeof(lst))
# list(map(lambda num:num*2, lst))


136


In [45]:
import numpy as np
arr = np.array(lst)
print(arr*2)
sys.getsizeof(arr)



[ 0  2  4  6  8 10 12 14 16 18]


184

In [ ]:
int -> float -> complex -> str

In [48]:
# Array is a collection of Homogeneous data
arr = np.array([10,20,30,40.50, 60+70j, 'A'])
print(arr)

['10' '20' '30' '40.5' '(60+70j)' 'A']


In [50]:
# Creating an array
# !pip install numpy
# %pip install numpy

You should consider upgrading via the 'pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [52]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr, type(arr))

[10 20 30 40] <class 'numpy.ndarray'>


In [56]:
# Checkig size, shape, dimension, element size
print(arr.size)

print(arr.shape)

print(arr.ndim)

print(arr.itemsize)

4
(4,)
1
8


In [58]:
# Creating a 2D array
arr = np.array(((1,2,3,4), (5,6,7,8), (9,6,3,0)))
print(arr)

print(arr.size)
print(arr.shape)
print(arr.ndim)


[[1 2 3 4]
 [5 6 7 8]
 [9 6 3 0]]
12
(3, 4)
2


In [62]:
# Creating an array using some builtin function in numpy
arr = np.arange(0, 10, 1)
print(arr)

arr = np.arange(0, 10, 0.5)
print(arr)


arr = np.arange(5, 25, 2)
print(arr)


[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[ 5  7  9 11 13 15 17 19 21 23]


In [64]:
arr = np.linspace(0, 9, 10)
print(arr)

arr = np.linspace(0, 9, 100)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8

In [66]:
arr = np.zeros((3,4))
print(arr + 8)

[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]


In [67]:
arr = np.ones((3,4))
print(arr * 8)

[[8. 8. 8. 8.]
 [8. 8. 8. 8.]
 [8. 8. 8. 8.]]


In [69]:
# Identity Matrix - Same no of rows and column - 
arr = np.eye(5)
arr * 8

array([[8., 0., 0., 0., 0.],
       [0., 8., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 8., 0.],
       [0., 0., 0., 0., 8.]])

In [70]:
# Empty Matrix

arr = np.empty((5,6))
arr


array([[2.00000000e+000, 2.00000000e+000, 1.08694442e-322,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [9.39262274e+165, 4.42514665e-062, 2.62396587e+179,
        2.33859552e-052, 1.10796057e-047, 3.83819517e+151],
       [3.98257296e+246, 4.50622044e-144, 3.80985069e+180,
        3.94255238e+180, 5.84968535e+199, 7.49874326e+247],
       [2.21537981e-062, 6.56210623e-091, 7.40906721e-038,
        5.10407683e-066, 2.25468612e+180, 5.49810101e-143],
       [1.26054259e-076, 2.54867596e-028, 5.87795372e-062,
        4.50615870e-144, 7.79952704e-143, 4.86670253e-051]])

In [96]:
# Changing the shape of an array
arr = np.arange(25, 55)
# arr

# reshape() methods reshapes an array
# arr2 = arr.reshape(5,6)
# print(arr2)
# print()
# print(arr)

# arr3 = arr.reshape(2,3,5)
# arr3

# reshaping an array using shape attribute
# arr.shape = 2,3,5
# print(arr)


# arr4 = arr.reshape(6, -10)
# print(arr4)

# arr.shape = 2,-1, 5
# arr


# Transposing an array
arr = arr.reshape(5,6)
# print(arr)
# print()
# print(arr.T)
# print()
# print(np.transpose(arr))
# print()
# print(arr)

# flattenning an array
print(arr)
print(arr.flatten())


[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]]
[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54]


In [107]:
# Basic Operations on array
arr1 = np.array([2,3,4,5,6])
arr2 = np.array([11,22,33,44,55])

In [108]:
# Arithemtic
print(arr1 + arr2)

print(arr2 - arr1)

print(arr1 * arr2)

print(arr2 / arr1)

print(arr2 // arr1)

print(arr2 % arr1)

print(arr2 ** arr1)


[13 25 37 49 61]
[ 9 19 29 39 49]
[ 22  66 132 220 330]
[5.5        7.33333333 8.25       8.8        9.16666667]
[5 7 8 8 9]
[1 1 1 4 1]
[        121       10648     1185921   164916224 27680640625]


In [120]:
arr1 = np.array([[1,22],[3,4]])
arr2 = np.array([[10,20],[30,40]])
print(arr1 + arr2)

[[11 42]
 [33 44]]


In [117]:
arr1 > arr2

array([[False,  True],
       [False, False]])

In [ ]:
# Product
# Scalar -  
# Vector

In [118]:
print(arr1 * arr2)

[[ 10 440]
 [ 90 160]]


In [122]:
# Vector product - No of columns in first arr and noof ros in second arr should be same

print(arr1.dot(arr2))
# [[ 1, 22],
# [ 3,  4]]

# [[10, 20],
# [30, 40]]

# [[670, 900],
# [150, 220]]

[[670 900]
 [150 220]]


array([[ 1, 22],
       [ 3,  4]])

In [131]:
arr1 = np.arange(12).reshape(2,2,3)
# print(arr1)
# print()
arr2 = np.arange(20,32).reshape(2,3,2)
# print(arr2)
# print()
print(np.dot(arr1, arr2))

[[[[ 70  73]
   [ 88  91]]

  [[268 280]
   [340 352]]]


 [[[466 487]
   [592 613]]

  [[664 694]
   [844 874]]]]


In [ ]:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]

[[[20 21]
  [22 23]
  [24 25]]

 [[26 27]
  [28 29]
  [30 31]]]


[[[[ 70  73]
   [ 88  91]]

  [[268 280]
   [340 352]]]


 [[[466 487]
   [592 613]]

  [[664 694]
   [844 874]]]]

In [134]:
# Compound Assignment 
arr1 += 2
arr1

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [138]:
# Aggregate Function - sum, max,min
arr1
np.sum(arr1)
np.max(arr1)
np.min(arr1)



4

In [139]:
arr1 = np.arange(25, 55).reshape(5, 6)
arr1

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [140]:
np.sum(arr1, axis = 0)  # axis = 0 => rows

array([185, 190, 195, 200, 205, 210])

In [142]:
np.max(arr1, axis = 0)

array([49, 50, 51, 52, 53, 54])

In [141]:
np.min(arr1, axis = 0)

array([25, 26, 27, 28, 29, 30])

In [143]:
np.sum(arr1, axis = 1)  # axis = 1 => cols

array([165, 201, 237, 273, 309])

In [144]:
np.max(arr1, axis = 1)

array([30, 36, 42, 48, 54])

In [145]:
np.max(arr1, axis = 1)

array([30, 36, 42, 48, 54])

# Indexing & Slicing

In [152]:
arr1 = np.array([10,20,30,40])
# print(arr1[0])
# print(arr1[-1])


arr1[1:4] = 100
arr1

array([ 10, 100, 100, 100])

In [162]:
arr2 = np.arange(25,55).reshape(5,6)
# print(arr2)

# print(arr2[1][2])
# print(arr2[1,2])

print(arr2[1][2])
print(arr2[1,2])

33
33


In [169]:
# Slicing
# print(arr2) 
print(arr2[1:3,2:4])

[[33 34]
 [39 40]]


In [170]:
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [172]:
arr2[2:, 3:]

array([[40, 41, 42],
       [46, 47, 48],
       [52, 53, 54]])

In [ ]:
32, 34
44, 46

In [175]:
arr2[1:4:2, 1:4:2]

array([[32, 34],
       [44, 46]])

In [183]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])
fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

In [186]:
row_ind = [0, 1, 1, 2]
col_ind = [0, 1, 3, 2]
fruit[row_ind, col_ind] = ['Watermelon', 'Muskmelon', 'Potato', 'Tomato']
fruit

array([['Watermelon', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Muskmelon', 'Plum', 'Potato'],
       ['Apricot', 'Apple', 'Tomato', 'Black berry']], dtype='<U11')